import React from "react";
const ProductData = [
  {
    id: 1,
    imgsrc: "/images/mango.webp",
    name: "Apple",
    fruitcategory: "Seasonal fruit",
    price: 100,
    discountprice: 200,
    rating: 4,
  },
  {
    id: 2,
    imgsrc: "/images/anaar.webp",
    name: "Pomegranate",
    fruitcategory: "Regular Fruit",
    price: 200,
    discountprice: 400,
    rating: 4,
  },
  {
    id: 3,
    imgsrc: "/images/green-apple.webp",
    name: "Green Apple",
    fruitcategory: "Regular Fruit",
    price: 400,
    discountprice: 800,
    rating: 5,
  },
  {
    id: 4,
    imgsrc: "/images/raddish.webp",
    name: "Raddish",
    fruitcategory: "Regular Fruit",
    price: 700,
    discountprice: 1400,
    rating: 4,
  },
  {
    id: 5,
    imgsrc: "/images/orange.webp",
    name: "Orange",
    fruitcategory: "Regular Fruit",
    price: 900,
    discountprice: 1800,
    rating: 4,
  },
  {
    id: 6,
    imgsrc: "/images/alphonsos.webp",
    name: "Alphonsos",
    fruitcategory: "Seasonal Fruit",
    price: 1000,
    discountprice: 2000,
    rating: 5,
  },
  {
    id: 7,
    imgsrc: "/images/sprout.webp",
    name: "Avocado",
    fruitcategory: "Regular Fruit",
    price: 1200,
    discountprice: 2400,
    rating: 3,
  },
  {
    id: 8,
    imgsrc: "/images/kiwi.webp",
    name: "Kiwi",
    fruitcategory: "Regular Fruit",
    price: 1000,
    discountprice: 2000,
    rating: 4,
  },
  {
    id: 9,
    imgsrc: "/images/brown-grapes.webp",
    name: "Brown Grapes",
    fruitcategory: "Regular Fruit",
    price: 800,
    discountprice: 1600,
    rating: 4,
  },
  {
    id: 10,
    imgsrc: "/images/donec-odio2.jpg",
    name: "Donec Odio",
    fruitcategory: "Seasonal Fruit",
    price: 1000,
    discountprice: 2000,
    rating: 5,
  },
  {
    id: 11,
    imgsrc: "/images/apple.webp",
    name: "Apple",
    fruitcategory: "Regular Fruit",
    price: 1500,
    discountprice: 3000,
    rating: 5,
  },
  {
    id: 12,
    imgsrc: "/images/banana.jpg",
    name: "Banana",
    fruitcategory: "Regular Fruit",
    price: 1600,
    discountprice: 3200,
    rating: 4,
  },
  {
    id: 13,
    imgsrc: "/images/carrot.webp",
    name: "Carrot",
    fruitcategory: "Seasonal Fruit",
    price: 1700,
    discountprice: 3400,
    rating: 5,
  },
  {
    id: 14,
    imgsrc: "/images/berrey.jpg",
    name: "Berrey",
    fruitcategory: "Seasonal Fruit",
    price: 1800,
    discountprice: 3600,
    rating: 3,
  },
  {
    id: 15,
    imgsrc: "/images/green-grapes.webp",
    name: "Green Grapes",
    fruitcategory: "Regular Fruit",
    price: 1300,
    discountprice: 2600,
    rating: 5,
  },
  {
    id: 16,
    imgsrc: "/images/rambutan.webp",
    name: "Rambutan",
    fruitcategory: "Seasonal Fruit",
    price: 1900,
    discountprice: 3800,
    rating: 2,
  },
  {
    id: 17,
    imgsrc: "/images/gwava.webp",
    name: "Gwava",
    fruitcategory: "Regular Fruit",
    price: 2000,
    discountprice: 4000,
    rating: 1,
  },
  {
    id: 18,
    imgsrc: "/images/pomelo.webp",
    name: "Pomelo",
    fruitcategory: "Seasonal Fruit",
    price: 2000,
    discountprice: 4000,
    rating: 3,
  },
  {
    id: 19,
    imgsrc: "/images/mongosteen.webp",
    name: "Mangosteen",
    fruitcategory: "Seasonal Fruit",
    price: 2000,
    discountprice: 400,
    rating: 5,
  },
  {
    id: 20,
    imgsrc: "/images/lychee.webp",
    name: "Lychee",
    fruitcategory: "Regular Fruit",
    price: 1400,
    discountprice: 2800,
    rating: 1,
  },
  {
    id: 21,
    imgsrc: "/images/mango1.webp",
    name: "Mango",
    fruitcategory: "Seasonalr Fruit",
    price: 1700,
    discountprice: 3400,
    rating: 2,
  },
];
export { ProductData };
